//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class findbusEntities : DbContext
    {
        public findbusEntities()
            : base("name=findbusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblaplicativo> tblaplicativo { get; set; }
        public DbSet<tblbairro> tblbairro { get; set; }
        public DbSet<tblbairrorua> tblbairrorua { get; set; }
        public DbSet<tblbase> tblbase { get; set; }
        public DbSet<tblcidade> tblcidade { get; set; }
        public DbSet<tblcidadebairro> tblcidadebairro { get; set; }
        public DbSet<tblitinerario> tblitinerario { get; set; }
        public DbSet<tbllogin> tbllogin { get; set; }
        public DbSet<tblponto> tblponto { get; set; }
        public DbSet<tblrota> tblrota { get; set; }
        public DbSet<tblrotaponto> tblrotaponto { get; set; }
        public DbSet<tblrua> tblrua { get; set; }
        public DbSet<tblruaponto> tblruaponto { get; set; }
        public DbSet<tblusuario> tblusuario { get; set; }
        public DbSet<tblversao> tblversao { get; set; }
    
        public virtual ObjectResult<USP_SEL_Itinerario_Result> USP_SEL_Itinerario(Nullable<int> codigoRota)
        {
            var codigoRotaParameter = codigoRota.HasValue ?
                new ObjectParameter("CodigoRota", codigoRota) :
                new ObjectParameter("CodigoRota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SEL_Itinerario_Result>("USP_SEL_Itinerario", codigoRotaParameter);
        }
    }
}
