//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaplicativo
    {
        public tblaplicativo()
        {
            this.tblversao = new HashSet<tblversao>();
        }
    
        public int AplicativoID { get; set; }
        public string LocalAPK { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
        public string VersaoAplicativo { get; set; }
    
        public virtual ICollection<tblversao> tblversao { get; set; }
    }
}
