//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBairroRua
    {
        public int BairroRuaID { get; set; }
        public int BairroID { get; set; }
        public int RuaID { get; set; }
    
        public virtual tblBairro tblBairro { get; set; }
        public virtual tblRua tblRua { get; set; }
    }
}
