//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBairro
    {
        public tblBairro()
        {
            this.tblBairroRua = new HashSet<tblBairroRua>();
            this.tblCidadeBairro = new HashSet<tblCidadeBairro>();
        }
    
        public int BairroID { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblBairroRua> tblBairroRua { get; set; }
        public virtual ICollection<tblCidadeBairro> tblCidadeBairro { get; set; }
    }
}
