//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbairro
    {
        public tblbairro()
        {
            this.tblbairrorua = new HashSet<tblbairrorua>();
            this.tblcidadebairro = new HashSet<tblcidadebairro>();
        }
    
        public int BairroId { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblbairrorua> tblbairrorua { get; set; }
        public virtual ICollection<tblcidadebairro> tblcidadebairro { get; set; }
    }
}
