//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbletinerario
    {
        public tbletinerario()
        {
            this.tblrotaetinerario = new HashSet<tblrotaetinerario>();
        }
    
        public int EtinerarioId { get; set; }
        public string DiaSemana { get; set; }
        public decimal HoraSaida { get; set; }
        public decimal HoraChegada { get; set; }
    
        public virtual ICollection<tblrotaetinerario> tblrotaetinerario { get; set; }
    }
}
