//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItinerario
    {
        public int ItinerarioID { get; set; }
        public int RotaID { get; set; }
        public string DiaSemana { get; set; }
        public string HoraSaida { get; set; }
        public string HoraChegada { get; set; }
    
        public virtual tblRota tblRota { get; set; }
    }
}
