//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int LoginID { get; set; }
        public int UsuarioID { get; set; }
        public string UsuarioSenha { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
