//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPonto
    {
        public tblPonto()
        {
            this.tblRotaPonto = new HashSet<tblRotaPonto>();
            this.tblRuaPonto = new HashSet<tblRuaPonto>();
        }
    
        public int PontoID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool PontoParada { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblRotaPonto> tblRotaPonto { get; set; }
        public virtual ICollection<tblRuaPonto> tblRuaPonto { get; set; }
    }
}
