//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblponto
    {
        public tblponto()
        {
            this.tblrotaponto = new HashSet<tblrotaponto>();
            this.tblruaponto = new HashSet<tblruaponto>();
        }
    
        public int PontoId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool PontoParada { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblrotaponto> tblrotaponto { get; set; }
        public virtual ICollection<tblruaponto> tblruaponto { get; set; }
    }
}
