//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRotaPonto
    {
        public int RotaPontoID { get; set; }
        public int RotaId { get; set; }
        public int PontoId { get; set; }
        public int OrdemPonto { get; set; }
        public decimal DistanciaPontoAnterior { get; set; }
    
        public virtual tblPonto tblPonto { get; set; }
        public virtual tblRota tblRota { get; set; }
    }
}
