//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrua
    {
        public tblrua()
        {
            this.tblbairrorua = new HashSet<tblbairrorua>();
            this.tblruaponto = new HashSet<tblruaponto>();
        }
    
        public int RuaId { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblbairrorua> tblbairrorua { get; set; }
        public virtual ICollection<tblruaponto> tblruaponto { get; set; }
    }
}
