//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrota
    {
        public tblrota()
        {
            this.tblitinerario = new HashSet<tblitinerario>();
            this.tblrotaponto = new HashSet<tblrotaponto>();
        }
    
        public int RotaId { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblitinerario> tblitinerario { get; set; }
        public virtual ICollection<tblrotaponto> tblrotaponto { get; set; }
    }
}
