//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblRota
    {
        public tblRota()
        {
            this.tblItinerario = new HashSet<tblItinerario>();
            this.tblRotaPonto = new HashSet<tblRotaPonto>();
        }
        [Display(Name="Código")]
        public int RotaID { get; set; }
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        [Display(Name = "Data Cadastro")]
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblItinerario> tblItinerario { get; set; }
        public virtual ICollection<tblRotaPonto> tblRotaPonto { get; set; }
    }
}
