//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRua
    {
        public tblRua()
        {
            this.tblBairroRua = new HashSet<tblBairroRua>();
            this.tblRuaPonto = new HashSet<tblRuaPonto>();
        }
    
        public int RuaID { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
    
        public virtual ICollection<tblBairroRua> tblBairroRua { get; set; }
        public virtual ICollection<tblRuaPonto> tblRuaPonto { get; set; }
    }
}
