//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public tblUsuario()
        {
            this.tblLogin = new HashSet<tblLogin>();
        }
    
        public int UsuarioID { get; set; }
        public string NomeUsuario { get; set; }
        public string UsuarioSenha { get; set; }
        public System.DateTime DataInclusaoRegistro { get; set; }
        public int NiveldoAcesso { get; set; }
    
        public virtual ICollection<tblLogin> tblLogin { get; set; }
    }
}
